#!/bin/bash

# Frontend deployment script for Cloudflare Pages

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

FRONTEND_DIR="frontend"

echo "Deploying frontend..."

# Always source setup-env.sh to ensure environment is configured
if [ -f "env.config" ]; then
    echo "Loading environment..."
    source setup-env.sh
    if [ -z "$PROJECT_NAME" ] || [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
        echo -e "${RED}Error: Failed to load environment variables!${NC}"
        echo "Please check your env.config file"
        exit 1
    fi
else
    echo -e "${RED}Error: env.config not found!${NC}"
    echo "Please create env.config from env.config.template and fill in your values"
    exit 1
fi

# Check if wrangler is installed
if ! command -v wrangler &> /dev/null; then
    npm install -g wrangler > /dev/null 2>&1
fi

# Check that env.js exists (generated by setup-env.sh)
if [ ! -f "frontend/env.js" ]; then
    echo "❌ frontend/env.js not found! Please run: source setup-env.sh"
    exit 1
fi

# Check if project exists, create if it doesn't
PROJECT_CHECK=$(wrangler pages project list 2>&1 | grep -w "$PROJECT_NAME" || true)

if [ -z "$PROJECT_CHECK" ]; then
    wrangler pages project create "$PROJECT_NAME" --production-branch=main > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "❌ Failed to create Cloudflare Pages project"
        exit 1
    fi
fi

# Deploy the frontend and capture output
DEPLOY_OUTPUT=$(wrangler pages deploy "$FRONTEND_DIR" --project-name="$PROJECT_NAME" 2>&1)

DEPLOY_STATUS=$?
if [ $DEPLOY_STATUS -ne 0 ]; then
    echo "❌ Failed to deploy to Cloudflare Pages"
    echo "$DEPLOY_OUTPUT"
    exit $DEPLOY_STATUS
fi

# Extract the project's stable domain
# The deployment URL contains a hash prefix, but the stable domain is project-name + random suffix
# Extract from deployment URL pattern: https://[hash].[project-name]-[suffix].pages.dev
DEPLOYMENT_URL=$(echo "$DEPLOY_OUTPUT" | grep -oE "https://[a-f0-9]+\.[a-zA-Z0-9-]+\.pages\.dev" | tail -1)
if [ -n "$DEPLOYMENT_URL" ]; then
    # Extract the stable domain part (everything after the first dot)
    STABLE_DOMAIN=$(echo "$DEPLOYMENT_URL" | sed 's|https://[^.]*\.||')
fi

echo "Frontend ready!"

if [ -n "$STABLE_DOMAIN" ]; then
    echo "https://${STABLE_DOMAIN}"
fi

echo ""
